@baseUrl = http://localhost:3000


### AuthController
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "douglasgmail.com",
  "password": "123456"
}


### AuthController
# @name changePassword
PATCH  {{baseUrl}}/auth/973c2870-9b28-49f9-9357-1b4cd107eff8/change-password
Content-Type: application/json

{
  "currentPassword": "999999999",
  "newPassword": "123456789"
}


### AuthController
# @name forgetPassword
POST {{baseUrl}}/auth/forget-password
Content-Type: application/json

{
  "email": "douglas@gmail.com"
}


### AuthController
# @name resetPassword
POST {{baseUrl}}/auth/reset-password
Content-Type: application/json

{
  "token": "106fa751b6715b8435b7fdbbb52566eb48906f689b96ad402f31d3755b5d8359",
  "tokenId": "93e98fa8c974a713e0f9fa693be94370",
  "newPassword": "123456"
}