@baseUrl = http://localhost:3000


### AddresController
# @name findAll
GET {{baseUrl}}/address


### AddresController
# @name findOne
GET {{baseUrl}}/address/4ca7f501-279c-43a0-b865-aeb1b8b39a91


### AddresController
# @name createOne
POST {{baseUrl}}/address
Content-Type: application/json

{
  "zipcode": "35701315",
  "street": "Rua Andirá",
  "number": 0,
  "complement": "",
  "neighborhood": "Aeroporto",
  "city": "Sete Lagoas",
  "state": "MG",
  "default": true,
  "userId": "c6740949-5a21-4510-a035-47c0a8d1b61a"
}


### AddresController
# @name updateOne
PATCH {{baseUrl}}/address/4ca7f501-279c-43a0-b865-aeb1b8b39a91
Content-Type: application/json

{
  "zipcode": "35700138"
}


### AddresController
# @name deleteOne
DELETE {{baseUrl}}/address/4ca7f501-279c-43a0-b865-aeb1b8b39a91
Content-Type: application/json